In [1]:
import random
import numpy as np

In [4]:

print(random.randint(0,100))

42


In [6]:
#this function produces random integer every time 
for i in range(5):
    print(random.randint(0,100))

25
41
74
34
56


In [7]:
#by setting the seed value , the function ensures that teh sequence of random numbers generated
#remains the same across multiple runs

for i in range(5):
    random.seed(42)
    print(random.randint(0,100))

81
81
81
81
81


In [15]:
from sklearn.model_selection import train_test_split
X,Y=np.arange(10).reshape((5,2)),range(5)
print(X,Y,sep="\n")


[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
range(0, 5)


In [11]:
#now every time we run this code different value would be allocated for 
#training and testing sets
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.33)
print(X_train,Y_train,X_test,Y_test,sep="\n")

[[0 1]
 [8 9]
 [4 5]]
[0, 4, 2]
[[2 3]
 [6 7]]
[1, 3]


In [13]:
#random state makes sure that every time same data points are sent for train and test sets
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.33,random_state=42)
print(X_train,Y_train,X_test,Y_test,sep="\n")

[[4 5]
 [0 1]
 [6 7]]
[2, 0, 3]
[[2 3]
 [8 9]]
[1, 4]


In [16]:
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.33,random_state=7)
print(X_train,Y_train,X_test,Y_test,sep="\n")

[[4 5]
 [2 3]
 [8 9]]
[2, 1, 4]
[[0 1]
 [6 7]]
[0, 3]
